/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CellRouteImport } from './routes/$cell'
import { Route as ApiCompleteRouteImport } from './routes/api/complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CellRoute = CellRouteImport.update({
  id: '/$cell',
  path: '/$cell',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompleteRoute = ApiCompleteRouteImport.update({
  id: '/api/complete',
  path: '/api/complete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$cell': typeof CellRoute
  '/api/complete': typeof ApiCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$cell': typeof CellRoute
  '/api/complete': typeof ApiCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$cell': typeof CellRoute
  '/api/complete': typeof ApiCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$cell' | '/api/complete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$cell' | '/api/complete'
  id: '__root__' | '/' | '/$cell' | '/api/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CellRoute: typeof CellRoute
  ApiCompleteRoute: typeof ApiCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$cell': {
      id: '/$cell'
      path: '/$cell'
      fullPath: '/$cell'
      preLoaderRoute: typeof CellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complete': {
      id: '/api/complete'
      path: '/api/complete'
      fullPath: '/api/complete'
      preLoaderRoute: typeof ApiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CellRoute: CellRoute,
  ApiCompleteRoute: ApiCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
